name: App Auth Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  demo:
    environment: TESTING
    runs-on: ubuntu-latest
    steps:
      - name: Debug APP_ID variable
        run: echo "APP_ID is ${{ vars.APP_ID }}"
      - name: Debug private key presence
        run: echo "Private key is set"
        if: ${{ secrets.PRIVATE_KEY != '' }}
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: committer
        run: echo "string=${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"  >> "$GITHUB_OUTPUT"
      - run: echo "committer string is ${{ steps.committer.outputs.string }}"
