name: App Auth Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  demo:
    environment: TESTING
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure app
        uses: actions/create-github-app-token@v2
        id: app-token
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      - name: Push new Branch
        id: push_new
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

          git checkout -b test-branch
          # git add . 
          # git commit -m "New Branch"
          git push
