name: App Auth Workflow
on:
  workflow_dispatch:

jobs:
  demo:
    environment: TESTING
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set up Git identity
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Change remote to use App token
        run: |
          git remote remove origin
          git remote add origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/m-alexeev/github-app-testing.git

      - name: Commit and push
        run: |
          git checkout -b new-branch
          git add .
          git commit -m "Auto-generated changes" || echo "Nothing to commit"
          git push origin --set-upstream new-branch
