name: App Auth Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  demo:
    environment: TESTING
    runs-on: ubuntu-latest
    steps:
      - name: Debug APP_ID variable
        run: echo "APP_ID is ${{ vars.APP_ID }}"

      - uses: actions/create-github-app-token@v2
        id: app-token
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id

      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

          git checkout -b test-branch
          git add . 
          git commit -m "New Branch"
          git push

          echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
