name: Trigger Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  dispatch:
    environment: TESTING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Dispatch Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/m-alexeev/dispatch-test/dispatches \
            -d "{\"event_type\":\"deployment-event\",\"client_payload\":{\"commit_sha\":\"${{ github.sha }}\"}}"
